### ISSUE TITLE
4-3: Update Todo

### ISSUE THREAD

**Issue by marcosandri-dev** [marcosandri-dev/todofullstack#10]
For now it's only the message but I will develop so that it will accept any body. 

- [x] Update Icon putting back input message form with message value
- [x] If EditMode = edit finally 
- [x] Send logic (very important) and API 
- [x] Slice update
