### ISSUE TITLE
4-1: Add todo 

### ISSUE THREAD

**Issue by marcosandri-dev** [marcosandri-dev/todofullstack#5]
Here is everything that's related to add a Todo. 

- [x] Button "New task" adds new line
- [x] Input field with submit button
- [x] Form send functionality
- [x] API to insert in "database"
- [x] Slice to take input data in state after API
